name: Deploy to GitHub Pages # Name des Workflows

on:
  push: 
    paths:
      - "index.html" 
    branches:
      - main 
# Bei der Änderung von index.html in der main branch wird der Workflow getriggert

jobs:
  deploy:
    runs-on: ubuntu-latest
# Umgebung in der der Workflow ausgeführt wird

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
# Läd den Code herunter in die Workflow Umgebung

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # Open Source github action um den deployment Prozess zu vereinfachen
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Offener Sicherheitstoken
          publish_dir: ./
          # Welcher Inhalt soll veröffentlicht werden (der vom Root verzeichnis)
#
